# Generated by Django 5.2.5 on 2025-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_framework_tracking", "0013_apirequestlog_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apirequestlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
